

export enum STATE_INPUT_CONTROL {
    DEFAULT = -1,
    ERROR = 0,
    OK = 1
}

export enum STATE_NAVEGATION {
    OPEN = 1,
    CLOSE = 0,
}

export enum TYPE_SPACE {
    INPUT_DISTANCE = 1,
    INPUT_DISTANCE_VERTICAL = 2,
    TEXT_DISTANCE_VERTICAL = 4,
    FORM_DISTANCE_VERTICAL = 3,
    TEXT_DISTANCE = 5
}